development:
    dialect: sqlite3
    datasource: CheckInBoard.db
    dir: migrations/sqlite3

production:
    dialect: postgres
    datasource: dbname=CheckInBoard sslmode=disable
    dir: migrations/postgres
    table: migrations
